directory: ~/music
library: ~/music/.data/musiclibrary.db

import:
    move: yes    # Move files to new location
    # copy: no   # Use files in place
    # write: no  # Don't modify tags

plugins:
  - musicbrainz  # Example plugin for fetching metadata
  - fetchart
  - lyrics
  # - ... other plugins you want ...
import:
  languages: en

fetchart:
  auto: yes       # automatically fetch art on import
  cautious: yes   # avoid overwriting existing art
  maxwidth: 500   # resize downloaded images

